//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Solutions.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_register
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string email_id { get; set; }
        public string contact_no { get; set; }
        public string password { get; set; }
        public string customer_address { get; set; }
    }
}
